// SPDX-License-Identifier: MIT
// Code generated by the Uniswap V2 Kit
// github.com/Uniswap/uniswap-v2-kit
// modifications made by SpaceSwap @0xwaya

pragma solidity >=0.5.0;

interface IUniswapV1Factory {
    function getExchange(address) external view returns (address);
}
